name: athena
description: "Your assistant you were promised"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.2.0  # For animations
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  
flutter_icons:
  android: true
  ios: true
  web: true
  windows: true
  macos: true
  image_path: "assets/icon/app_icon.png"  # Your app icon

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
